# -*- coding: utf-8 -*-
"""AluraStoreLatam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18S7s_TpkSNo_nGWQGo12BInzFvOzgZPe

### Importación de datos
"""

##pip install pandas

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""#1. Análisis de facturación


"""

df = pd.concat([tienda, tienda2, tienda3, tienda4], ignore_index = True)

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.normalize('NFKD')
    .str.encode('ascii', errors='ignore')
    .str.decode('utf-8')
)

facturacion_total = df.groupby('lugar_de_compra')['precio'].sum().reset_index()
facturacion_total.columns = ['lugar_de_compra','facturacion_total']
print(facturacion_total)



"""# 2. Ventas por categoría"""

categorias_populares = df['categoria_del_producto'].value_counts().reset_index()
categorias_populares.columns = ['Categoria', 'total_vendidos']
print(categorias_populares)



"""# 3. Calificación promedio de la tienda

"""

calificacion_promedio = df.groupby('categoria_del_producto')['calificacion'].mean().reset_index()
print(calificacion_promedio)



"""# 4. Productos más y menos vendidos"""

producto_mas_vendido = df['producto'].value_counts().head(5)
producto_menos_vendido = df['producto'].value_counts().tail(5)
print('#==los cinco productos mas vedidos==#')
print(producto_mas_vendido)
print('#==los cinco producto menos vendido==#')
print(producto_menos_vendido)



"""# 5. Envío promedio por tienda"""

envio_promedio = df['costo_de_envio'].mean()
print('El costo de envio promedio general es:')
print(envio_promedio)
round(envio_promedio, 2)

envio_promedio_tienda = df.groupby('lugar_de_compra')['costo_de_envio'].mean().reset_index()
print('costo promedio de envio por tienda es')
print(envio_promedio)